version: '3.9'
services:
  frontend:
    container_name: frontend-notes-app
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - '80:80'
    networks:
      - network
    depends_on:
      - backend
  
  backend:
    container_name: backend-notes-app
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - '8080:8080'
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql-notes-app
    image: mysql:8.0.31-oracle
    restart: always
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: notes
      MYSQL_PASSWORD: notes
    ports:
            - "3306:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    networks:
      - network

networks:
  network:
    driver: bridge
