keycloak:
#  server-url: http://keycloak:8080
  server-url: http://localhost:8081
  realm-name: app
  clients:
    - id: frontend-web
      redirect-url: http://localhost:4200/*
  users:
    - username: test
      password: test
      roles:
        - USER
    - username: user
      password: user
      roles:
        - USER
